language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: iCnARnX44nSGcS8VkvsWbMJDHAnCHCvKLtScHlG8n9oDoYXIG3JCZ557eYJF78KbeTGFQiTW2kDi4/DwnTYiZSmPWveEkeNYDxwF7JlX89yeaepbJbfakY+CMjVxz8NdDbHTHl2eRoqoVg8rXqsudjA7rTzjCuI6RF/oe2fhWbcWUe4cdxOPwEl+STovPc79euLoC2AHwrS98RE8aki7D3bhhy8FYeiUbLdTgHk5XFPzRQohTFLJHkApU+uGuYsuh1Aw8PDhXuFmXsbbg2u87o58PKjSdg92dkumDWaxZ/F5MEbui1ths4ygaksFvXWTvWpRbdN4iDqYdu9B0p+1g3W972qhpwafOVayg0XaInrKmwiaCxOHjfCLsJNHxHs2Y2RO0FWGdJ21BPMuMwn9IP3vMpZ8sHkCwH8VaMLjhYNHvjFloBgPbCqItrd5XjObx/DevQ9i6WjwNzvL0FAa+NBPbrzTXx79xqmDzDI2hY52DcKLuCOwUNWbSk4FBFC/DgDGP4uJF5ps97fUoiQa3/pL6wStpa3nUxwLDCaZNQT9AfMi3rhIbM9aBFi+q/+vxfSZgFsZBIJmTJZ2jc2Rf3ny4s/PGN62XlIuqoZmB1qLVQz7aTijBHNFYtUE0Fc0BkoRv75lEL3feL3EEd17xJnzMJbV1Hh80sPXoiFI+ak=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: kY8y74Yn1nJZBlVfoKu9Fkkq4N5a5qAdXvr9EzpvHkT5FK1s1MSsbwlA97ZnKuwH5TuSuD0hofh+Dp/9JnzFPS3Ac0iFZT2ZMb4XGnsd9guxvTohA3rVc+d7V+lX3VXS2gm62Qz/QnkKYknNW62muEAJxUuGzd14YEaKEErtASPqKp84r02aD5Fog7VeloeeQLdjKmdnCSYbJp0B0S5jqmTaawwx+SOjb/C6DIgK+O3dSQrcV/rTw2IG2Ns7SnFb1pGn4Aamd0AuYivWrdkVcxhfTfVu1ejtaBdFuXP6a4b2Nq4T7SN6Zh/G6/acVGv8gYZ+G3pK25U4JSPFJ+QI5W93LollgBiCwUj1GYDC1CCPghzb5LHIMqi7STFdhNuL6677L9teu65EGVirmMedU2szHZamx34L16myaEstaZRC5owoAZvh0J+FCl5kAS9+baDEyaj5bg2bPhhPCy31UJz86SQGimR3xirAI03yTumsJdMvAEovNvAD0068U5BUUFokzTYBKkagBo7OFFIPhBhpgwnDhLj34qLuo5CT5FvQnrSdaHl2Z9M95weIwWjdmtoIVn8WxL3tJ7vEYvdqh7DmE4QDuQA+4IK4unCeX1czxNBGoNO+V47n/HRKDZ49mGe+ZqDRO/dtOngjOAfwLVNyvHU8dpZOMqrm2Hb9uvE=
  - secure: p4e0NO3KL1q+spdA26QMohUJ5Csj/6nC6ctsBMik/8LPOALIWgsqh5bnVOopRL/p/0n4G9b/ZnUZ/3icauCZBklGGQWmdBlqOB2IYpNvkvCU+OHLwp5PfBeqafbWSsgGcdxHscuY0iHTHTaF8AUoRvZvjpfr98bSA9G1UhyjQ5ST+YTiNQuEeQ5aBAAe05XKWrm5ManKUW9Ut4mjhG7JcYaLZ6cxvkU0pJzBe2cnaiP+xhrrNRWrPspwX5Fx3CjlQ67M/uHFL5TkSn4jVzf8OX/sxh926Y1ocv74YVS/XGvm56RnyLwCa/LSfpU4miN40beVUdLQCnlwvL/CU86jphGR9No+be3yZj0qdoOaulzqFF26CAB6eBLnj7ciobioLwbWu5d3y67+/jbeLy8/7wWaOLJEH7rwuzdeZs6Sk0iiyuR1+FLcoUmalVz5+iu4WD4zhVwv/atsjqxNBSHI+Y6ry5WCUqgItTuXamE7Y9+ivLNXc60s6aOkJZqqpw7x9PHNQxxZUqSFsB58NkePT2dgUdcG0slTv5+vtvHR1j1l2cPEgxF2aVXNk4kEgzr/gfxiiZy5UlSiHJn1BoWiEwiOcgsvc3Ad9LWqb9H09dAcr5soXVKaP8H8guxy2m179pHILDGbTgEIHop/FsmbWaohN1HloQFLkwD8+ZARd3w=
  - secure: MYU3ro/T3VI2dOQOkS6D3hJTSM7VPziBxLZSDbqWp9Xpg/T84QsMyW0mP2xYbIDXETQvbxBH6X9XSJigkNqm4PCEmEprlHx6fmzY/BtRP3lXPfw/V14HMrlTfj5Jg5R2EbseBYWmg2mgCxTiJl4ksoF/+IV96uO7eycEeR2JqsKzbV/C2364rxfws6vtkZOXl7HTgVknsP9FazleXXKOs7QTN3WONgXqDUlLCVt/6wLIk5KgvI1kKFlHt2s8PX1ynApJNurE8zPClssj3nRKAJLV2RaG/s1u4nvMGkZIx85Gck3ERgREVsBCKtpTl4uZS59u5901qistJ7PQZiNwcjgk/82zpclgw3bblPIxMjcXxyXriNqKV65bi3+I7Tx/JhVPJlH73jkPVaEd6IZ8tLLkq4eTDLiE3ztuIeJGlFUXuQh4iVRye8IemFlzfbulTLTlB0zG/h9Z28zA+gOoyGTPLlNmktaHi+vuwnZIC1bnaC0QSv8TA4pNc/0a1l/ssVWRMhTytUxg8Irg1GaLEibUSlP/y0jY7CVSfrO4yf+6CMww3TFlXvV1VGRyL17dGmwjC5mULNgBRQUA0HjkRmUxPCcoqc/CSWsSUYVmnrZWbG8GWlsTY3GnB+AC/OwgyiWAfVh/cCM9XmG6PxvL31nHwgJ7ACGSIDExNMtkMhk=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- export BUILD_NAME=scc-onlinedogshow-daemon-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- wget https://archive.apache.org/dist/kafka/0.10.1.1/kafka-0.10.1.1-src.tgz -O kafka.tgz
- mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
- echo "auto.create.topics.enable=true" >> kafka/config/server.properties
- nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
- sleep 10
- nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
- sleep 10
- kafka/bin/kafka-topics.sh --zookeeper 127.0.0.1:2181 --create --topic kafka-test-topic --partitions 3 --replication-factor 1
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
